pipeline {
      agent {
            docker {
                image 'say-hello:latest'
            }
        }
    triggers {
        pollSCM '* * * * *'
    }
    stages{
        
      stage('Build') {
            steps {
                     sh 'bash -c "if fuser -s 8081/tcp; then fuser -k 8081/tcp; echo \'Killed process on port 8081\'; else echo \'No process is running on port 8081\'; fi"'
                sh 'mvn clean package'
            }
        }
         stage('build-docker') {
            steps {
               dir('src') {
                         sh 'cp -r Dockerfile /var/lib/jenkins/workspace/say-hello/target/'
                }
             dir('target') {
                  sh 'docker build -t say-hello .'
                  }
            }
        }
    }        
    
}
