pipeline {
    agent any
    triggers {
        pollSCM '* * * * *'
    }
    stages{
        
      stage('Build') {
            steps {
                sh 'mvn clean package'
            }
        }
         stage('build-docker') {
            steps {
                  sh 'cp -r var/lib/jenkins/workspace/say-hello/src/Dockerfile /var/lib/jenkins/workspace/say-hello/target/'
             dir('target') {
                  sh 'docker build -t say-hello .'
                  }
            }
        }

      stage('deploy-server') {
            steps {
                dir('target') {
                  sh 'java -jar say-hello-0.0.1.jar'
               }
            }
        }
    }        
    
}
